"""
bioBakery Workflows: tasks.files module
A collection of file names used by tasks

Copyright (c) 2017 Harvard School of Public Health

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import os
import copy
import sys

from .utilities import name_files

class FileInfo(object):
    def __init__(self, name=None, subfolder=None, tag=None, extension=None, description=None):
        # set a list of non-path keywords
        self.non_path_keywords=["description"]
        
        # concat multiple strings if present in description
        if description and isinstance(description,basestring) or isinstance(description,tuple):
            description="\n".join(description)
        
        keywords={"names":name, "subfolder":subfolder, "tag":tag, "extension":extension, "description":description}
        self.keywords = {key:value for key, value in keywords.items() if value}
        
    def get_path_keywords(self):
        info = copy.copy(self.keywords)
        
        # remove the non-path keywords
        for key in self.non_path_keywords:
            try:
                del info[key]
            except KeyError:
                pass
        
        return info
    
    def __getitem__(self, key):
        """ Return the file info """
        try:
            value=self.keywords[key]
        except KeyError:
            value=""
        return value

class Workflow(object):
    @classmethod
    def path(cls, name, main_folder, none_if_not_found=None, error_if_not_found=None, **keywords):
        merged_keywords = copy.copy(keywords)
        merged_keywords.update(cls.file_info[name].get_path_keywords())
        file_path=name_files(folder=main_folder, **merged_keywords)

        # if set, error if the file does not exist
        if error_if_not_found and not os.path.isfile(file_path):
            message="\nERROR: Unable to find file: "+file_path
            desc=cls.description(name)
            if desc:
                message+="\n\nFile description:\n"+desc
            sys.exit(message)
        
        # if set, check if the file exists, if not return None
        if none_if_not_found and not os.path.isfile(file_path):
                file_path = None
            
        return file_path
    
    @classmethod
    def description(cls,name):
        try:
            desc=cls.file_info[name].keywords["description"]
        except (KeyError, AttributeError):
            desc=""
            
        return desc
    
    @classmethod
    def list_file_path_description(cls,folder,input_files):
        """ List the file names and descriptions in a format to be used in an argument help description """
        
        desc=""
        for required in input_files:
            desc+="\n\n".join(["* "+cls.path(name,folder)+ " ( " + required + " )\n-- "+cls.description(name) for name in input_files[required]])+"\n"
            
        return desc

class ShotGun(Workflow):
    # set the folder names for wmgx_wmtx data workflows
    wmgx_folder_name="whole_metagenome_shotgun"
    wmtx_folder_name="whole_metatranscriptome_shotgun"
    
    file_info={}
    
    # set the kneaddata file name
    file_info["kneaddata_read_counts"]=FileInfo("kneaddata_read_count_table.tsv",subfolder="counts",
        description=("A tab-delimited file with samples as rows and read counts as columns.",
            "This file is generated by compiling information from the KneadData log files. ",
            "The file contains read counts after each step of the Kneaddata workflow. ",
            "Depending on the input to Kneaddata this file will contain counts for ",
            "single or paired/orphan reads."))

    # set the taxonomy file names
    file_info["taxonomic_profile"]=FileInfo("taxonomic_profiles.tsv",
        description=("A tab-delimited file with samples as columns and relative abundance as rows.",
            "This file contains the merged taxonomic profiles computed by MetaPhlAn2 for all samples."))
    file_info["species_counts"]=FileInfo("metaphlan2_species_counts_table.tsv",subfolder="counts",
        description=("A tab-delimited file with samples as rows and counts as columns.",
            "This file contains the counts of total species for each sample using the ",
            "species identified by MetaPhlAn2."))
    
    # set the merged feature file names
    file_info["genefamilies"]=FileInfo("genefamilies.tsv",
        description=("A tab-delimited file with samples as columns and gene families ",
            "as rows. This file is a merged set of gene families for all samples ",
            "computed by HUMAnN2. This file contains stratified counts as RPKs."))
    file_info["ecs"]=FileInfo("ecs.tsv",
        description=("A tab-delimited file with samples as columns and ecs as rows. ",
            "This file is a merged set of ecs for all samples generated from the gene ",
            "families computed by HUMAnN2. This file contains stratified counts as RPKs."))
    file_info["pathabundance"]=FileInfo("pathabundance.tsv",
        description=("A tab-delimited file with samples as columns and pathways ",
            "as rows. This file is a merged set of pathway abundances for all ",
            "samples computed by HUMAnN2. This file contains stratified counts ",
            "of non-normalized abundances."))
    
    # set the normed feature file names
    file_info["genefamilies_relab"]=FileInfo("genefamilies_relab.tsv")
    file_info["ecs_relab"]=FileInfo("ecs_relab.tsv")
    file_info["pathabundance_relab"]=FileInfo("pathabundance_relab.tsv")
    
    # set the feature count file names
    file_info["genefamilies_relab_counts"]=FileInfo("humann2_genefamilies_relab_counts.tsv", subfolder="counts")
    file_info["ecs_relab_counts"]=FileInfo("humann2_ecs_relab_counts.tsv", subfolder="counts")
    file_info["pathabundance_relab_counts"]=FileInfo("humann2_pathabundance_relab_counts.tsv", subfolder="counts")
    
    # set the all feature counts file names
    file_info["feature_counts"]=FileInfo("humann2_feature_counts.tsv", subfolder="counts",
        description=("A tab-delimited file with samples as rows and features ",
            "as columns. This file includes the total feature counts (non-stratified)",
            "for the features computed by HUMAnN2 (genes, ecs, and pathways)."))
    file_info["humann2_read_counts"]=FileInfo("humann2_read_and_species_count_table.tsv",subfolder="counts",
        description=("A tab-delimited file with samples as rows and counts as columns.",
            "This file was created using the HUMAnN2 logs. It includes the total number ",
            "of species used to generate the custom database, the total number of initial",
            "reads, and the total reads aligning for both search steps."))
    
    # set the names for the rna/dna normed files
    file_info["genefamilies_norm_ratio"]=FileInfo("rna_dna_relative_expression_unstratified.tsv",subfolder=os.path.join("norm","genes"),
        description=("A tab-delimited file with samples as columns and genes as rows. ",
            "This file includes the normalized RNA abundances as a ratio to DNA abundance. ",
            "This file does not include stratified features."))
    file_info["ecs_norm_ratio"]=FileInfo("rna_dna_relative_expression_unstratified.tsv",subfolder=os.path.join("norm","ecs"),
        description=("A tab-delimited file with samples as columns and ecs as rows. ",
            "This file includes the normalized RNA abundances as a ratio to DNA abundance. ",
            "This file does not include stratified features."))
    file_info["paths_norm_ratio"]=FileInfo("rna_dna_relative_expression_unstratified.tsv",subfolder=os.path.join("norm","paths"),
        description=("A tab-delimited file with samples as columns and pathways as rows. ",
            "This file includes the normalized RNA abundances as a ratio to DNA abundance. ",
            "This file does not include stratified features."))

class SixteenS(Workflow):
    
    file_info={}

    # set the names for the otu table and read count files
    file_info["otu_table_closed_reference"]=FileInfo("all_samples_taxonomy_closed_reference.tsv",
        description=("A tab-delimited file with samples/taxonomy as columns and taxonomy as rows. ",
            "First column is the OTU id and the last column is the taxonomy. The remaining",
            "columns are sample names. Values are counts."))
    file_info["read_count_table"]=FileInfo("all_samples_read_counts.tsv",
        description=("A tab-delimited file with samples as rows and counts as columns. ",
            "The counts included are the original read count, total number of reads ",
            "mapping to an OTU with known taxonomy, and total reads mapping to an ",
            "unclassified OTU."))
    
    
        